### ISSUE TITLE
Document Knative component

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#247]
And make sure it's published in the Camel website

**Comment by arthurdm** [comment]
+ 1 This would be very helpful.  In particular, which ones can scale to 0, etc.

**Comment by lburgazzoli** [comment]
@nicolaferraro 

I guess that when you think about having component published on the main camel website you mean in the camel-k documentation and not part of the official camel components right ? 

Asking because:
1. it has a different groupId `org.apache.camel.k`
2. it is still dependant on some camel-k specific bits
