### ISSUE TITLE
Main runtime depending on Log4j core

### ISSUE THREAD

**Issue by christophd** [apache/camel-k-runtime#414]
The ApplicationSupport in camel-k-runtime-main module depends on Log4j core in order to do on-the-fly Logger configurations. 

See
https://github.com/apache/camel-k-runtime/blob/master/camel-k-main/camel-k-runtime-main/src/main/java/org/apache/camel/k/main/ApplicationSupport.java#L25

This makes it impossible to run Camel K main runtime with logging frameworks other than Log4j core.

The runtime should depend on Log4j API or a logging abstraction framework such as SLF4j instead. This way users can run Camel K with whatever logging framework they like.

**Comment by lburgazzoli** [comment]
that's by design as we don't want to have multiple logging options. note that once camel-k will migrate to quarkus, the supported logging framework will be jboss-logginh

**Comment by christophd** [comment]
depends on the target use cases for the runtime in general. 

the camel-k examples given in the repo (https://github.com/apache/camel-k-runtime/tree/master/examples) gave the impression to me that users can also use the runtime as part of a normal Maven project (no operator involved). this might lead to the situation where people just want to use some logging framework other than log4j.

**Comment by lburgazzoli** [comment]
it was the case in the earliest stages but it turned out to be problematic so we assumed the runtime would also bring the right logging impl so we can retain the same behavior among runtimes.

we can certainly separate main for the logging impl but then the operator would need to explicit add a dependency on log4j impl and we decided to avoid adding specific deps by the operator; however we ca use the camel k catalog to do the achieve this goal but it will become obsolete as soon as we'll replace camel-k-runtime-main by camel-k-runtime-quarkus as the only supported runtime

**Comment by christophd** [comment]
it does not make much sense to separate things in terms of logging now if we already know that it will become obsolete as soon as we have a single supported runtime in quarkus in future. so feel free to close this one if you want

**Comment by lburgazzoli** [comment]
I guess the main driver for the question is because of the integration tests in syndesis right ?

In that case we should check if at least in jvm mode it would be possible to use something different from jboss-logging in quarkus otherwise we could end up in the same issue and if not, if we can support jboss logging for syndesis ITs
