### ISSUE TITLE
Can't set Knative broker name

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#535]
Issue #151 talks about params like `brokerApiVersion` and `brokerName` as ways to set the source/target broker, but they are not present in the codebase.

While we can just use `apiVersion` (which is already present), setting `brokerName` (or better, just `name`) in the URI results in an error.

Parameter `name` is an URI endpoint when using `knative:endpooint` and `knative:channel`, but not with `knative:event`.

**Comment by lburgazzoli** [comment]
It does not work because `name` is a path param so for `endpoint` and `channel` the name is already part of the uri however for `event`, name is used to identify the event type.

To fix it I think we have 3 options:
1. rename the path param from `name` to `id` and introduce `name`
2. use better name to set kubernetes resource, like `resourceName`, `resourceType`, `resourceApiVersion`
3. rename the path param from `name` to `id` and use better name to set kubernetes resource

**Comment by nicolaferraro** [comment]
Option 1 seems the most backward compatible. How would `name` behave for `endpoint` and `channel`?

**Comment by lburgazzoli** [comment]
Name is only used to look up resource definitions from knative env so it is an internal detail
